#!/bin/dash

# test if .shrug already exists
# else make .shrug, index, commit_log, status file, and echo message
if test -d ".shrug"
then
    echo "shrug-init: error: .shrug already exists" >&2
    exit 1
else
    mkdir -p .shrug
    mkdir -p .shrug/index
    touch ".shrug/.commit_log.txt"
    touch ".shrug/.status.txt"
    touch ".shrug/.branches.txt"
    echo "Initialized empty shrug repository in .shrug"
fi

exit 0